version: "3"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=bq
      - POSTGRES_PASSWORD=secret
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'    
  admin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    expose:
      - '80'
    ports:
      - '8080:80'
  node:
    image: node:12 # https://hub.docker.com/_/node/
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8888
      DB_URL: postgresql://bq:secret@db:5432/postgres?schema=public
      JWT_SECRET: secret-token
      ADMIN_EMAIL: postgres@postgres.com
      ADMIN_PASSWORD: secret
    volumes:
      - ./:/home/node/app # montamos el codigo en el HOME del usuario _node_
    expose:
      - 8888 # nuestra app corre en el puerto 8080
    ports:
      # mapeamos el puerto 8080 de nuestro contenedor al puerto 80 de nuestra
      # máquina
      - 80:8888
    # reinstalamos las dependencias y levantamos el servidor
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - postgres
    networks:
      - public
      - private
volumes:
  postgres:
networks:
  public:
    internal: false
  private:
    internal: true
